{'TIME':2022-01-03 10:40:41,100,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:40:45,602,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:40:56,945,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:41:02,649,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:42:21,219,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:42:22,314,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:42:50,671,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:43:53,503,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:43:54,411,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:48:08,683,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 10:48:47,823,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividades?CTIPSER=T&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'QUERY': RESPUESTA VACIA:
        SELECT cCodExa, cCodAct, tActCit, tActAte, tActFin, cCodPla, cUsuFir, cUsuCod,
            c_TipSer, cDesSer,
            cDesDoc, cNroDni, cNroDoc, cNombre, tNacimi, nEdad, cDesSex,
            cDesTip, cDesPue, 
            cNroRuc, cDesEmp, cDesSed,
            c_Aptitu, cDesApt,
            c_Estado, cDesEst,
            cDesPer,
            c_TipPla, tPlaIni, tPlaFin, cVauche
        FROM V_ACTIVIDAD_1
        WHERE c_TipSer = 'T'AND c_Estado != 'F'}}
{'TIME':2022-01-03 11:03:35,122,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': DATOS : ERROR EN EJECCION, 'DETAIL':None}}
{'TIME':2022-01-03 11:10:08,880,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': 'CDESSER', 'DETAIL':None}}
{'TIME':2022-01-03 11:12:07,767,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': DATOS : RESPUESTA VACIA, 'DETAIL':None}}
{'TIME':2022-01-03 11:21:01,858,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': 'CDESSER', 'DETAIL':None}}
{'TIME':2022-01-03 11:44:17,129,'ADDRESS':'127.0.0.1','URL': 'http://localhost:4000/actividad/PDF?CCODACT=00017192&CTIPSER=R&CCODPLA=72539751001&CNRODNI=99999999&CNRORUC=20125327509&CCODUSU=9999','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': timed out, 'DETAIL':None}}
{'TIME':2022-01-03 12:30:41,783,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': 'NoneType' object is not subscriptable, 'DETAIL':None}}
{'TIME':2022-01-03 14:25:01,456,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': 'CDESSER', 'DETAIL':None}}
{'TIME':2022-01-03 14:31:31,823,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': PRINT NO DEFINIDO CODIGO: A, 'DETAIL':None}}
{'TIME':2022-01-03 15:20:54,741,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': PRINT NO DEFINIDO CODIGO: A, 'DETAIL':None}}
{'TIME':2022-01-03 15:23:08,415,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': print_actividad() missing 1 required positional argument: 'lcCodExa', 'DETAIL':None}}
{'TIME':2022-01-03 15:29:45,557,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': print_actividad() missing 1 required positional argument: 'lcCodExa', 'DETAIL':None}}
{'TIME':2022-01-03 15:30:29,642,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': DATOS : ERROR EN EJECCION, 'DETAIL':None}}
{'TIME':2022-01-03 15:35:19,910,'ADDRESS':'127.0.0.1','URL': 'http://127.0.0.1:4000/actividad/detalle','TYPE':'ERROR','MODULE':'Actividad','MSG':{'USER':9999, 'DATA': DATOS : ERROR EN EJECCION, 'DETAIL':None}}
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/subtitulos?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/subtitulos?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/subtitulos?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/subtitulos?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/extra?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/extra?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/extra?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/extra?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/cie10?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/cie10?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/cie10?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/cie10?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/subtitulos?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/subtitulos?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/subtitulos?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/subtitulos?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/extra?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/extra?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/extra?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/extra?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/cie10?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/cie10?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/cie10?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/cie10?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/subtitulos?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/subtitulos?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/subtitulos?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/subtitulos?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/extra?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/extra?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/extra?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/extra?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:43:02,453,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'base_events','MSG':{Future exception was never retrieved
future: <Future finished exception=MissingSchema("Invalid URL '/actividad/cie10?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/cie10?CCODACT=00017192&CCODUSU=9999?")>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/actividad/cie10?CCODACT=00017192&CCODUSU=9999': No schema supplied. Perhaps you meant http:///actividad/cie10?CCODACT=00017192&CCODUSU=9999?
{'TIME':2022-01-03 16:44:30,325,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x21daadbaa08 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 16:44:30,326,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x21daadc0988 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 16:45:23,755,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8d3a988 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 16:45:23,775,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8d504c8 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 16:45:23,786,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8d4aa08 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 16:45:23,804,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f7660948 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 16:45:23,820,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8d25d48 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 17:03:00,266,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8deab88 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 17:03:00,268,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8ded848 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 17:03:00,294,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8def4c8 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 17:03:00,303,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8d76cc8 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
{'TIME':2022-01-03 17:03:00,313,'ADDRESS':'None','URL': 'None','TYPE':'ERROR','MODULE':'_base','MSG':{exception calling callback for <Future at 0x1c5f8dea308 state=finished returned Response>}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
