{'TIME':2022-02-08 11:32:39,736,'ADDRESS':'127.0.0.1','URL': 'http://localhost:4000/plan/PDF?CCODACT=72539751002','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving //plan/PDF}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskAPI\app\decorators.py", line 16, in secure_function
    secure_function.attrib = request.args["CCODUSU"]
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'CCODUSU'
{'TIME':2022-02-08 11:33:06,469,'ADDRESS':'127.0.0.1','URL': 'http://localhost:4000/plan/PDF?CCODACT=72539751002','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /plan/PDF}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\CLANAD_PY\FlaskAPI\app\decorators.py", line 16, in secure_function
    secure_function.attrib = request.args["CCODUSU"]
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\werkzeug\datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'CCODUSU'
{'TIME':2022-02-08 11:44:59,792,'ADDRESS':'127.0.0.1','URL': 'http://localhost:4000/plan/consentientos?CCODPLA=72539751002&CCODUSU=9999','TYPE':'ERROR','MODULE':'channel','MSG':{Exception while serving /plan/consentientos}}
Traceback (most recent call last):
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\channel.py", line 397, in service
    task.service()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\waitress\task.py", line 434, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Administrador.WIN-DUOGLHGMSST\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1702, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'plan.planconsentientos' did not return a valid response. The function either returned None or ended without a return statement.
